# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'networkLayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for networkLayer
  pod 'ProgressHUD', :git => 'https://github.com/relatedcode/ProgressHUD.git', :commit => '83c3801e9aa69be157a47c40cdd8702bfaf29213'
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end

end
